describe('Settings STT mode (browser + mocked dev bridge)', () => {
  it('changes transcription mode and persists via save_settings', () => {
    cy.visit('/')
    cy.get('button[aria-label="Settings, click to open"]').click()
    cy.contains('button', 'Audio & Dictation').click()
    cy.contains('h3', 'Speech-to-Text Mode').scrollIntoView()
    cy.get('.stt-mode-cards button').contains('.mode-name', 'Hybrid').click()
    cy.wait(600)
    cy.reload()
    cy.get('button[aria-label="Settings, click to open"]').click()
    cy.contains('button', 'Audio & Dictation').click()
    cy.contains('h3', 'Speech-to-Text Mode').scrollIntoView()
    cy.get('.stt-mode-cards button').contains('.mode-name', 'Hybrid').parent().should('have.class', 'active')
  })
})
